name: 'Sirene'
description: 'Send Dependabot alerts to Discord.'
author: '@0xTeles'
inputs:
  TOKEN:
    description: 'GitHub Personal Access Token'
    required: true
  WEBHOOK:
    description: 'Discord Webhook URL'
    required: true
runs:
  using: 'node16'
  main: 'build/index.js'